apiVersion: v1
kind: Secret
metadata:
  name: secret-common
type: Opaque
stringData:
  JWT_SECRET: "CHANGE_ME_PROD_JWT_SECRET_KEY"
  REDIS_HOST: "redis-cache-prod-master"
  REDIS_PASSWORD: "CHANGE_ME_PROD_REDIS_PASSWORD"
