apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-user-service
  namespace: phonebill-dg0504
data:
  SERVER_PORT: "8081"
  DB_KIND: "postgresql"
  DB_PORT: "5432"
  DDL_AUTO: "update"
  REDIS_DATABASE: "0"
  SHOW_SQL: "true"